### ISSUE TITLE
Game Icon

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#168]
Open Realm of Stars should have own icon. Now it seems to be defaulting for Java icon. I am not going to assign this to a milestone.

**Comment by tuomount** [comment]
Icon should work in all three operating systems: Windows, OS X and Linux. I can only test the linux side.

**Comment by janimakinen** [comment]
I could try to look into this and make a suggestion.

**Comment by tuomount** [comment]
Yes, feel free to look into this.

**Comment by tuomount** [comment]
Apparently this was easier than I expected. Ready for verifying.

**Comment by tuomount** [comment]
Works from installation package. Closing.
