### ISSUE TITLE
[Feature-Request] Remove terrifying sound during compilation

### ISSUE THREAD

**Issue by naclander** [tuomount/Open-Realms-of-Stars#178]
This game looks pretty cool, and I quickly cloned the repo and tried running `mvn install` During the process, I believe some unit test were being run that produced sound. I definitely did not expect compiling the game to produce and noise, and since my volume at the time was turned up pretty loud I also found it quite terrifying . Please disable this if possible.

**Comment by tuomount** [comment]
Sorry, about that I left those sounds there when sound was implemented that I can verify that sound is actually working. Disabling should not be problem since, CI machines does not have sounds enabled either. Fixing this should be easy I try to do this in 0.6.0 release.

**Comment by tuomount** [comment]
This was easy fix. Needs to be verified.

**Comment by naclander** [comment]
I can confirm no more sound is playing. Resolving.
