### ISSUE TITLE
Unique ship interior for each space race

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#239]
There could be unique ship interior for each space race. Make this much of new graphics is huge task, so I won't place this for certain milestone. These can be added when ever these are done.

- [x] Human ship interior
- [x] Greyan ship interior
- [x] Spork ship interior
  Bridge should have somekind of throne
- [x] Centaur ship interior
- [x] Mechion ship interior
  It should have very small windows, since machines does not need see outside
- [x] Teuthidae ship interior
- [x] Homarian ship interior
- [x] Scaurian ship interior
  Bridge should look like a cargo ship, something like in Aliens movie
- [x] Mothoid ship interior
  Interior could have somekind of hivecomb look a like
- [x] Chiraloid ship interior
- [x] Pirate ship interior

**Comment by janimakinen** [comment]
These bridges look cool! 👍

**Comment by tuomount** [comment]
Added bridge for mechion. Bridge has quite big windows but it has many retro looking computers with lots of bright lights.

**Comment by tuomount** [comment]
Works now. Closing.
