### ISSUE TITLE
Colonist count when loading colony ship is acting weird

### ISSUE THREAD

**Issue by Replicant7e4** [tuomount/Open-Realms-of-Stars#304]
Preconditions:
* Colony ship is on a planet with at least two colonists available
Steps to reproduce:
* Go to fleet view. Colonist count is 0/2
* click + to add new colonist on ship. Colonist count is now 1/2
* click + to add new colonist on ship. 

Result:
* Colonist count is now 2/0.

Expected result: 
* Colonist count should be 2/2

**Comment by tuomount** [comment]
This is even more complex. Second number is telling how many free places are in whole fleet. This same free space is shared with metal. So one cargo space can hold either up to two population or up to 10 metals. If one metal is added then in same cargo space cannot be added any population. Same goes if population is added then no metal cannot be added there.

So if fleet has  two empty cargo space it can hold following: up to 4 population but no metal, or 20 metal and no population or up to 2 population and 10 metal.

So last number in both metal and population show possible free space but if space is used then this last number is shown as zero.

**Comment by tuomount** [comment]
Seems to be working now. Closing.
