### ISSUE TITLE
NPE when the population button in the planet view is clicked

### ISSUE THREAD

**Issue by Replicant7e4** [tuomount/Open-Realms-of-Stars#306]
Preconditions:
* Game is just started

Steps to reproduce:
* Go to planet view
* Press the population button.

Result:
See the attached file:
[npe.txt](https://github.com/tuomount/Open-Realms-of-Stars/files/3751928/npe.txt)

**Comment by tuomount** [comment]
Bug happens planet has null variable called underConstruction. This same bug is when rushing with credits but it is not visible since there are no credits available when game starts.

**Comment by tuomount** [comment]
Works now. Closing.
