### ISSUE TITLE
No production selected when the game is started

### ISSUE THREAD

**Issue by Replicant7e4** [tuomount/Open-Realms-of-Stars#309]
Currently there is no project selected automatically for production, when the game is started and it is hard to see it. To fix this, there should be a default project selected (extra credit?)

**Comment by tuomount** [comment]
This could fixed so that when turn is changing and before planet starts handling the production it would check if underConstruction is null and then select extra credit if planet owner is human player.

**Comment by tuomount** [comment]
Hmm This was fixed already for 0.13.0Beta. Closing this one. Issue was missing milestone.
