### ISSUE TITLE
If there are unassinged leaders, make a message about it

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#372]
This should be rather easy issue. If there is unassigned leader there should be message about it. This chance would only affect on human player.

**Comment by MH-jpg** [comment]
Hi, I'm new in open source and I would like to start with this issue as my first one. Is it possible?

**Comment by tuomount** [comment]
Hi. Yes this would be possible. You need to look code in AITurnView.java method handleLeaders(). In same loop where all leaders are looped through, this check should be done. How message is created look how it is created when leader dies. Easiest way to test this is start playing when get the new leader as quickly as possible and not assigned it. If government type is kingdom or empire those will get heirs and when they turn 18 heir is unassigned.

**Comment by tuomount** [comment]
@MH-jpg  Are you doing this or should I set this back unassigned?

**Comment by MH-jpg** [comment]
Hi, sorry it takes so long.. Yes Im working on it, but I have lots of unplanned work during these week. I hope it could be done in next couplne days.

**Comment by MH-jpg** [comment]
Hi @tuomount , please check #387

**Comment by tuomount** [comment]
Works. Closing.
