### ISSUE TITLE
Sound effect for Ion cannon

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#376]
Ion cannon is added as rare tech. It now uses same sound as photon torpedo. It should use another one. Remember add correct attributions to credits.

**Comment by EikeSan** [comment]
Hello @tuomount can you check my PR #379 . 😄

**Comment by tuomount** [comment]
I'll take a look.

**Comment by tuomount** [comment]
[plasmaioncannon.save.zip](https://github.com/tuomount/Open-Realms-of-Stars/files/5428550/plasmaioncannon.save.zip)

Attached save game where one human ship has both Ion cannon and plasma cannon weapons on board. That ship is next to space pirate station ready to attack. Easiest way to find this is simple click next message and ship is there ready to move. When fleet is select you can move it against pirate station by right clicking it.

I had to increase volume of both of these sound effects they were not loud enough.

**Comment by tuomount** [comment]
Closing issue.
