### ISSUE TITLE
Carrier ships should not require cargo space

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#384]
Freighters which contain fighter bays should not require to have cargo space. In theory this should be easy fix. "No cargo space!" is error message in ship design, which would be good point to start checking if this is easy fix.

**Comment by Pa3cia07** [comment]
Hi, I´m interested in your project, but I am new one in open source. If this issue is still actually, I would like to work on it. :)

**Comment by tuomount** [comment]
Yes, you are welcome to participate. I'll assign this for you.

**Comment by Pa3cia07** [comment]
thank you so much!

**Comment by Pa3cia07** [comment]
Could you get me steps to replicated in game, please? ´Cause I think, I solved issue, but I don´t know where I can verify it in game.

**Comment by tuomount** [comment]
I'll attach save game where are Fighter Bay Mk2 already research. Now all you need to do is make freighter ship full of these until there is no cargo space left.

Save game. Just place this into saves folder and load it. Then go to ships and make a new ship design something like in attached screenshot.
[Steel_AI.save.zip](https://github.com/tuomount/Open-Realms-of-Stars/files/5513329/Steel_AI.save.zip)


See screenshot what kind of design needs to be done and which is not legal in current master:
![Screenshot-1604956457896-5835](https://user-images.githubusercontent.com/15839156/98597401-a66bca00-22e1-11eb-89e0-0514042b8384.png)

**Comment by tuomount** [comment]
Do you have any estimate when this would be done? There is still one issue which is not in wait for verify expect this one.

**Comment by Pa3cia07** [comment]
I am really sorry, I lost in the game and I don´t know solve this issue.

**Comment by tuomount** [comment]
No harm done, I'll do it. Thanks for trying.

**Comment by tuomount** [comment]
Works now. Closing.
