### ISSUE TITLE
Ship Component Jammer 

### ISSUE THREAD

**Issue by wksdn18** [tuomount/Open-Realms-of-Stars#49]
<img width="609" alt="2017-04-05 7 00 08" src="https://cloud.githubusercontent.com/assets/26127534/24700600/945ace44-1a32-11e7-9738-98f8018c3490.png">

I think Jammer Component doesn't have the damage.

How about to change the method from comp.getDamage() to comp.getDefenseValue()????

<img width="429" alt="2017-04-05 7 00 53" src="https://cloud.githubusercontent.com/assets/26127534/24700614/a14524b0-1a32-11e7-921b-452776252056.png">

**Comment by tuomount** [comment]
Yes, it should be defenseValue instead of damage. I changed that and create JUnit for this. Could you please verify the commit and close this issue?

**Comment by Krlucete** [comment]
Okay I got it!!!! Thank you!!!
