### ISSUE TITLE
method damageBy in Ship.java

### ISSUE THREAD

**Issue by Krlucete** [tuomount/Open-Realms-of-Stars#52]
<img width="562" alt="2017-05-08 10 14 04" src="https://cloud.githubusercontent.com/assets/16019322/25805803/f7a61c42-343b-11e7-80fd-70fa0d69eca6.png">

I think ShipDamage.value should be 0. Because value 1 is meaning that no damage, not even dent.
Please Check about this!!!

**Comment by tuomount** [comment]
Yes, it should be 0. Shield gets lower so it is more than just dent.

**Comment by Krlucete** [comment]
Good!
