### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by aequis** [tuomount/Open-Realms-of-Stars#53]
I tried using mvn install and Eclipse to build the project, but it won't build.  

It seems like most of the errors (and there are a lot of them) say the following:
Description	Resource	Path	Location	Type
Mockito cannot be resolved	CombatAnimationTest.java	/Open-Realms-of-Stars/src/test/java/org/openRealmOfStars/player/combat	line 139	Java Problem

Any idea what could be wrong? I'm on Windows 10 and using JDK/JRE 1.8, btw.

**Comment by tuomount** [comment]
Seems that paths are in unix style and which probably does not work in Windows. I'll need to check if
Maven in Windows needs some special configuring to get it work. How ever I cannot verify this fix since I do not have Windows machine available.

**Comment by tuomount** [comment]
Could you paste here more about the error log Maven is giving?

**Comment by aequis** [comment]
[log.txt](https://github.com/tuomount/Open-Realms-of-Stars/files/1076853/log.txt)

I might be wrong, but I feel like it could be related to the project's structure and its dependency on JRE 1.7, since 1.7 isn't available on Windows anymore. It's been obsoleted by Oracle in favour of 1.8.

**Comment by tuomount** [comment]
Looks like you are missing Mockito library. Maven should fetch it from Maven repository. Have allowed Maven to access internet? This was mentioned in Maven's Window's troubleshoot.

**Comment by tuomount** [comment]
Could you please confirm if this help for your issue?

**Comment by tuomount** [comment]
Closing this one.
