### ISSUE TITLE
Bump minimum Java version

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#637]
**Java 1.7**, currently targeted by the project, is outdated and out of support for many years now. While it is nice to have backwards compatibility and that the game also tends to "just work", this is a bit of an extreme.

If backwards compatibility with Java is very important, could the project target at least **Java 8**?  
It is actually supported by vendors, *and comes with nice language features, like lambda expressions*.

I personally would just bump it to **Java 17**, since it is quite recent, some other games are already using it (so player may already have it), and has even more language features, including type inference via `var` keyword, `record` types and text blocks.

**Comment by tuomount** [comment]
I think there isn't anything that prevents Open Realm of Stars running with latest Java. 

I could move to Java11 that seems to be LTS and is provided by Ubuntu repositories by default so it is nice and easy to install.
