### ISSUE TITLE
Split LeaderUtility class

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#642]
`LeaderUtility` class is massive, having some 2800 lines of code in it.
Out of those, roughly 1000 lines are directly responsible for process of selecting next leader as a realm's ruler.

This code should be split from LeaderUtility, because:
1. LeaderUtility class implements core behavior of governments.
   Therefore, the class does something that it should not do.
2. The code would be more structured and the `LeaderUtility.java` file shortened by 1000 lines.

**Comment by tuomount** [comment]
Leaders have been working fine. Closing.
