### ISSUE TITLE
License text placement in files is wrong

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#644]
Text of GNU GPL license, along with copyright notices, is essentially in all `.java` files placed incorrectly, **implemented as Javadoc comment for class in the file**. Because of this, class's documentation (including a context one in IDEs) is mixed with the license text. This in turn renders class's documentation unreadable, as it is "spammed" by the license.

The GNU GPL text, along with copyright notices, should be inside normal comment, not Javadoc one. And it makes sense to put it
at top of the file, probably under (or above) the `package` statement.

**Comment by tuomount** [comment]
Yes, this is true. I think it should under package statement. Are you interested to fixing this? This should be done for all java files at same time. No other changes when doing that so it would be easy to review.

**Comment by tuomount** [comment]
I think when I started the project that style was then recommended and it has stick from there. It would look a bit weird of some of the classes would have it under package statement and in comment and some in above class statement and javadocs. And no I do not have regex trick for this, if I had this issue would not be here :smile:
