### ISSUE TITLE
Numbers in Research may overflow and break it

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#648]
There is a bug related to research, that occasionally causes visible integer overflow. It happens when artifact is researched and the research bonus is way higher than "research needed" in a field.

![research-overflow](https://github.com/tuomount/Open-Realms-of-Stars/assets/62666666/2684960a-a535-4092-ae3a-eedc22ec1c31)

Apart from being a visual bug, this can also **completely break research in the affected research field!** This happens, I presume, when player has order of magnitude higher research production than is required by the field, which was disrupted already by the artifact bonus and *focuses* on it.
Then, the field "how long until next tech" will go from the obviously overflown value to values like -3. Next turn, research in that field will stop unlocking techs.

![research-broken](https://github.com/tuomount/Open-Realms-of-Stars/assets/62666666/011eeb0b-ad88-4428-a999-52b85c4fd393)

## How to reproduce

1. Concentrate all research on single field.
2. Discover and research an artifact, that affects any neglected field.
3. Observe the label "how long until next tech" in research view show overflowed value.
4. Have very high research prodution at that time.
5. Try to "focus" on the research of overflown field.
6. Label will show incorrect negative value or zero.
7. Research in that field will stop working completely, presumably forever.

**Comment by tuomount** [comment]
That -3 kind of overflow was partially intentional or I left it as it is since it kind of hints how many techs one might get when ancient artifact has been received, but yes showing 0 star years is equally just fine. That other one is obvious bug.

**Comment by tuomount** [comment]
Works now. Closing.
