### ISSUE TITLE
Refactor and cleanup LeaderStats and Perks

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#651]
Leader `Perk` code contains logical error inside contract of how perks should work. At least according to the scraps of Javadoc. Although majority of the code expects there are not duplicate perks, the code actually does not check this inherently on several places and this condition is checked by hand instead.

The `LeaderStats` class is handling the stats in a primitive `switch`y way. This is hard to read and adds a lot of boilerplate code.

**Comment by tuomount** [comment]
Leaders have been working fine. Closing.
