### ISSUE TITLE
Deduplicate Game's Credits

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#653]
Game contains internal Credits screen. This screen shows the same text as `AUTHORS.md`, because that file is generated by the game with a special command-line option. Although the credits are authoritatively written in the game, `AUTHORS.md` is also kept in repository and may fall out of sync with game.

Because `AUTHORS.md` file is much superior to hardcoding authorship information to Java strings, the `AUTHORS.md` should become authoritative source of truth for game's credits.

**Comment by tuomount** [comment]
Works closing.
