### ISSUE TITLE
Current Playing Song overlay harms player UX

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#668]
While briefly displaying current playing song on song change looks like a good idea on paper, in practice it doesn't work well. It is detrimental to player's User eXperience (UX) in two ways currently, one being fundamental to the feature, other being bug in implementation.

## Player UX

As a player, I want to concentrate on the game. Big, white overlay popping-in and overlaying the thing I am concentrating on disrupts me. Game should not disrupt the player while playing. Background music should just enhance the gaming experience.

Additionally, there is a bug with the overlay. It is capturing input, which is *extremely annoying* in some cases, when it may completely block player's actions. *Player cannot do what they want to do, because of the overlay.* This is particularly notable issue in diplomacy and planetary screens, where it often hides fundamental parts of said screens, forcing the player to wait for the overlay's disappearance.

## Programming point of view

- 160+ lines and 1 file implementing it can be deleted, while *increasing* value for the player.
- It will be one feature less that has to be maintained.

If approved for removal, I can submit Pull Request for this immediately.

**Comment by tuomount** [comment]
I kept thinking of this, since it suppose to work if player moves mouse cursor over it it should disappear faster, but it seem that only text goes darker, but does not disappear faster. So that's a bug in current implementation.

I also see that annoying sometimes, some maybe it is better just to remove.

**Comment by tuomount** [comment]
Works now. Closing.
