### ISSUE TITLE
RaceTrait "goodness" scoring

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#697]
As mentioned in GH-673, `RaceTrait`s could have some score / points to represent how beneficial (or detrimental) given trait is from a game-play point of view.

The point scale should be very small, something like `-5 to +5`, to make it easily understandable and simple to reason about:
- 5 being a total game-breaker
- 3 is rather noticeable
- 1 is minor benefit/malus
- 0 is neutral (trait may change game-play, but it compensates for this by itself)

Benefits of such system are:
- **Helps developer to balance the game** - It can point out that a race is having too many benefits without compensation
- Player has clue how good the trait is - **Improves UX for new players**, as they don't have to guess "Is this good?"
- *It allows dynamic `RaceTrait` assignment to races* - Could be used for procedural generation of races, in random events, etc...
- Better visualization - Traits can be sorted and/or colored by their "goodness"

I have the implementation mostly ready, just posting this to get approval before submitting a PR.

**Comment by tuomount** [comment]
Yes, this definitely needs to be done. Also maximum radiation level should have effect on points, but this can be done later. This is also required for custom races. If you have implementation mostly ready, please finish it up and make pull request.

**Comment by tuomount** [comment]
Maybe radiation could be converted similarly traits as gravity and temperature. There could be four levels:
No radiation, Low radiation, high radiation and Very high radiation. Space race would get similarly trait radiation tolerance. Radiosynthesis then would gain just extra food based on radiation level: No radiation - 0 food, Low radiation - 3 food, High radiation - 6 food, Very high radiation - 9 food. Radiation well and dampener would simple lower radiation for one level. This would also alter star map generation.

**Comment by tuomount** [comment]
Works now. Closing.
