### ISSUE TITLE
Moving Diplomacy SpeechLines to data files

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#728]
During diplomacy, communication between participants is handled with `SpeechLine`s.
`SpeechLine` is carrying both "what kind of speech it is" (`SpeechType`) and the "flavor text" of the line itself (`String`).
`SpeechLine`s are generated by `SpeechLineFactory`, where all the texts are hardcoded, for each `SpaceRace`.

Proposed design:
1. A set of "speeches" would be called `SpeechSet`.
2. `SpeechSet` can be used as component for realm/race to represent what kind of "flavor text" will be used in diplomacy.
3. There should be no direct coupling between Realm/SpaceRace and `SpeechSet`.
4. Speech data is stored in JSON *object*. Treating JSON file as single object should not be done.
5. `SpeechSet` could have "tags" to define some of it's properties, like being agressive/calm, related to some physique feature of speaker, etc...
   *This could be used to create loose coupling between speech and realm/race.*

There are some things that one has to be aware of:
1. `SpeechType`/`SpeechLine` are types used for **bi-directional communication**.
   Request and reply are of the same Java type. *Evaluation of what to do depends on context and `SpeechType` in request/reply.*
2. There are no true IDs for text in `SpeechLine` itself. `SpeechType` is used as "ID".
3. Because of 1. and 2., **there is one reply, which has different text but same type.** (AFAIK reaction to war declaration)
   1. This requires either new `SpeechType` for it if `SpeechType` will be used as "IDs" for the
   2. Or make the text data use different IDs

**Comment by tuomount** [comment]
Reason why I did the JSON first, I wanted to try it if it could work out, but then I noticed reading speeches in that format would not be easy that DataLoader. It would need to have extra class something like SpeechSet.

I can add add the ACKNOWLEDGE_WAR SpeechType.

**Comment by tuomount** [comment]
Okay, I did not first get what you meant by `ACKNOWLEDGE_WAR`. But yes, now createAgreeWithWarLine is called as any other speechline and has it's own type, which is `ACKNOWLEDGE_WAR`.

Removed also special thing that robots could not get angry.
