### ISSUE TITLE
SpaceRace enum dehardcoding

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#729]
Part of #666. This serves as tracking issue for "de-enumerating" `SpaceRace`,
as it requires many parts of the game to not depend directly on `SpaceRace` `enum`.

Known existing blockers are:
- [x] `SpeechFactory` and speech data (tracked in #728)
- [x] Ship image bound to `SpaceRace`, rather than to some ID -> ID could be referenced by `PlayerInfo` or `SpaceRace` in emergency
- [x] Spork bonus ships at start -> Either convert to "hack" `RaceTrait` or remove the feature
- [x] Human "unique star system" -> Probably "hack" with `RaceTrait` temporarily.
- [x] Tech "presets" by race -> Either direct  "hack" `RaceTrait`s or assign the Tech based on **proper** `RaceTrait`s (like living in zero-G, being robotic, etc.)
- [x] Some code in StarMap that assigns planetary workforce
- [x] The "image alignment" system for diplomacy screen rendering
- [x] Space ship bridge HUE color lamp effects
- [x] SpaceRace theme music
- [x] Leader NameGenerator 
- [x] Research handling is based on space race
- [x] Background generator

The list may be incomplete, those are just things I know about.

**Comment by tuomount** [comment]
Spork bonus ship could be removed, since all those spaceraces require new balancing any way.
That image alignment and ship images could be just pointer to another object/class in SpaceRace class eventually.

**Comment by tuomount** [comment]
> There was at least one case where _pseudo-race's_ ID in `createOne()` method was wrongly written. I suggest to create a static constant and use it instead of writing it each time. Also, using the `Optional<>` or `createOr()` methods can help to detect such cases, as it forces programmer to _explicitly_ say, what to do in case that value is absent, possibly throwing an error when something goes awry. (I found it. It is in Diplomacy.java, text `SpaceRaceFactory.createOne("SPACE_PIRATES"));` It is possible there are other such cases.)
> 
Good catch, I had these bunch of place with _. Using static would be much bettter.

> Regarding design, if you plan to ever introduce "races created at runtime" (procedurally-generated or similar), the `SpaceRaceFactory` class usage and code will likely have to be revised dramatically. This is because of the (dreaded) **global state**. It is still very "enumish" and thus _not_ suitable for such design - in case of `RaceTraits`, `Buildings`, "Bridge Graphics", etc. global state is not such a deal-breaker, as those objects are likely to be predefined before program launch (by programmer/modder) and work as available "blocks to build from". Races are more a thing that "can be built from the available blocks" at runtime (think like Planets vs. Buildings - Buildings are predefined in data files, their individual "setup" on a Planet is not).
> 

My idea was to add space race editor directly into main menu. When player click load game or new game then SpaceRaces would reinitialized. Currently there is no way to do, but it should be just static method that calls singletons init() method.
In actual editor there should be warning if space race is deleted that old save files might not fuction anymore.

> So technically, the `SpaceRaceFactory` now works as a "race _preset_ loader". And by quick glance, a whole lot of code is still designed to treat `SpaceRace`s as "globally available information" rather than "ad-hoc data". Usage of the `createOne()` method of the factory can help to find such cases. Removing the global-state of `SpaceRace` data will also likely include things like saving race data to save files or something. But since `SpaceRace` is normal class with normal objects now, potential removal of the global state is at least conceivable. 😄
> 
> And if you do not plan to add "races made at runtime", and leave this to "modding" only, then everything's great!
> 

That editor from main menu is a bit like tool for modding. Just easier UI than opening JSON editor.

> In any case, the removal of the `SpaceRace` `enum` is still a **major** step forward. 👍

Yes, I agree.

**Comment by tuomount** [comment]
There are no more SpaceRace enum. Closing.
